@startuml
'https://plantuml.com/sequence-diagram
partition 客户端 {
  (*) --> "定时任务开启"
  --> "发送心跳包"
  "返回识别码" --> "读取返回识别码"
    --> if "nRet" then
  --> [-1] "心跳包请求错误"
  --> "记录错误日志"
  --> (*)
  else
  --> [0] "心跳请求无数据"
  --> "系统时间与收发数据包时间差 "
  --> if "(心跳阈值时间是否大于发包时间) 且 重试次数< 阈值次数"
  --> [超过] "设置重复次数加1"
  --> "发送心跳包"
   else
   --> [未超过] (*)
   endif
  else
  --> [1] "有数据"
  if "是否有超时记录" then
  --> [有] "更新系统时间"
  --> "配置判断"
  else
  --> "配置判断"
  endif
  if "是否有配置" then
    --> [有] "客户端读取配置"
    --> "解析并写入配置"
    --> "更新发包时间"
    else
    --> [没有] "更新发包时间"
  endif
  endif
   --> (*)
}

partition 服务端接口  {
   "发送心跳包" --> "接受心跳包数据"
   --> "合法性检查"
   if "检查认证权" then
   --> [检查失败] "阻断接口"
   -->(*)
   else
   --> [检查成功] "服务端更新收包时间"
   endif
   "服务端更新收包时间"--> "时钟检查"
   if "心跳包发送时间戳与当前服务器时间误差在范围内" then
    --> [不在范围内] "记录超时日志"
    --> "返回当前系统时间与时间戳超时标记"
    --> "返回 nRet = 1"
   else
   --> [在范围内] "是否有需要更新的配置"
   endif
   if "服务器判断需要读取配置" then
   --> [是] "读取配置"
   "读取配置" --> == S3 ==
   == S3 == --> "记录读取日志"
   else

   --> [否] "返回 nRet = 1"
   endif
   --> "服务端记录收包时间"
   "服务端记录收包时间" --> "返回识别码"
}

partition 数据库  {
    == S3 == --> "读取对应公司配置"
    --> "设置配置已经读取"
   "记录读取日志" --> == S4 ==
   "设置配置已经读取" --> == S4 ==
    --> "返回 nRet = 1"
}
@enduml